services:
    nginx :
      build: ./requirements/NGINX
      ports:
        - 443:443
      depends_on:
        - wordpress
      volumes:
        - wp:/var/www/html
      networks:
        - internal_network
      restart: on-failure
    db :
      build: ./requirements/MariaDB
      env_file: .env
      volumes:
        - mariadb:/var/lib/mysql
      networks:
        - internal_network
      restart: on-failure
    
    wordpress:
      build: ./requirements/WordPress
      volumes:
        - wp:/var/www/html/
      depends_on:
        - db
      env_file:
        - .env
      networks:
        - internal_network
      restart: on-failure


volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mel-hous/data/db
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mel-hous/data/wp

networks:
  internal_network:
    name: 'internal_network'
    driver: bridge