FROM debian:buster

RUN apt-get -y update && apt-get -y install nginx  && apt-get install -y tini

# RUN mkdir -p /var/sitweb/html

COPY  ./tools/index.html /var/www/html

COPY  ./tools/mel-hous.jpeg /var/www/html

# COPY  ./my_nginx.conf /etc/nginx/conf.d

ENTRYPOINT ["/usr/bin/tini", "--"]

CMD [ "nginx", "-g", "daemon off;" ]