services:
    nginx :
      build: ./NGINX
      ports:
        - 443:443
      depends_on:
        - wordpress
      volumes:
        - wp:/var/www/html
      networks:
        - internal_network
      restart: on-failure
      # volumes:
      #   - nginx:/var/lib/mysql
    db :
      build: ./MariaDB
      env_file: .env
      volumes:
        - mariadb:/var/lib/mysql
      networks:
      - internal_network
      restart: on-failure
    
    adminer:
      image: adminer
      ports:
        - 8080:8080
    
    wordpress:
      build: ./WordPress
      volumes:
        - wp:/var/www/html/
      depends_on:
        - db
      restart: on-failure
      environment:
        - DOMAIN_NAME=$DOMAIN_NAME
      env_file:
        - .env
      ports:
        - 9000:9000
      networks:
        - internal_network
    

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /goinfre/Inception/data/db
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /goinfre/Inception/data/wp

networks:
  internal_network:
    name: 'internal_network'
    driver: bridge